### ISSUE TITLE
Event highlight on homepage overflows on mobile

### ISSUE THREAD

**Issue by djacu** [Socal-Nix-User-Group/socal-nug#24]
# *Overfull \hbox (9.895pt too wide)*

<img src="https://github.com/Socal-Nix-User-Group/socal-nug/assets/7043297/7c1090c7-c199-4893-811d-07d0b4c83a4c" width="400">

**Comment by davidnuon** [comment]
Closed as of https://github.com/Socal-Nix-User-Group/socal-nug/commit/4fe5cac7f3257a01ab48b43dd288ed93f8df1b69
