### ISSUE TITLE
Socal vs SoCal

### ISSUE THREAD

**Issue by RossComputerGuy** [Socal-Nix-User-Group/socal-nug#52]
Example: https://socal-nug.com/faq/
> What makes the Socal NUG so dynamic?

With Southern California shortened as "Socal", it can easily be mistaken as "Social". By shortening it as "SoCal", the capital C makes it easier to identify as being "Southern California". The capital C also goes well with the capital C in California. Should we change this?

**Comment by sarcasticadmin** [comment]
I think this makes it clear :+1:
